/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.HQ;

public final class R {
    public static final class array {
        /**  Used in View/Spinner1.java 
         */
        public static final int colors=0x7f050000;
        public static final int reciter_values=0x7f050002;
        public static final int reciters=0x7f050001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int playbackpause=0x7f020001;
        public static final int playbackstart=0x7f020002;
    }
    public static final class id {
        public static final int sp_reciter=0x7f070001;
        public static final int sp_translation=0x7f070002;
        public static final int txt_index=0x7f070003;
        public static final int txt_num_verses=0x7f070006;
        public static final int txt_num_verses_lbl=0x7f070007;
        public static final int txt_prefTitle=0x7f070000;
        public static final int txt_rev_order=0x7f070009;
        public static final int txt_rev_order_lbl=0x7f070008;
        public static final int txt_suraName=0x7f070005;
        public static final int txt_tname=0x7f070004;
        public static final int txt_verse_num=0x7f07000a;
        public static final int txt_verse_txt=0x7f07000b;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int preferenceslist=0x7f030001;
        public static final int surarow=0x7f030002;
        public static final int verselist=0x7f030003;
        public static final int verserow=0x7f030004;
    }
    public static final class string {
        public static final int app_name=0x7f060001;
        public static final int hello=0x7f060000;
    }
    public static final class xml {
        public static final int data=0x7f040000;
        public static final int preferences=0x7f040001;
    }
}
