/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.HQ;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int txt_index=0x7f060000;
        public static final int txt_num_verses=0x7f060003;
        public static final int txt_num_verses_lbl=0x7f060004;
        public static final int txt_rev_order=0x7f060006;
        public static final int txt_rev_order_lbl=0x7f060005;
        public static final int txt_suraName=0x7f060002;
        public static final int txt_tname=0x7f060001;
        public static final int txt_verse_num=0x7f060007;
        public static final int txt_verse_txt=0x7f060008;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int surarow=0x7f030001;
        public static final int verselist=0x7f030002;
        public static final int verserow=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int hello=0x7f050000;
    }
    public static final class xml {
        public static final int data=0x7f040000;
    }
}
